In [1]:
import tensorflow as tf

In [4]:
# init of tensors
x = tf.constant(4,shape=(1,1),dtype=tf.float32)
xa = tf.constant([[1,2,3],[4,5,6]])

xb = tf.ones((3,3))
xc = tf.zeros((2,3))
xd = tf.eye(3) # identity matrix
print(xd)
print(xc)
print(xb)
print(xa)


tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
a = tf.random.normal((3,3),mean=0,stddev=1)
print(a)

tf.Tensor(
[[ 0.84113675  1.0200719  -1.6842017 ]
 [ 2.287922    0.47923258 -1.1106135 ]
 [ 0.23269473  1.2963169  -0.04353718]], shape=(3, 3), dtype=float32)


In [8]:
b = tf.random.uniform((3,3),minval=5,maxval=10)
print(b)

tf.Tensor(
[[5.968794  9.746869  9.176566 ]
 [5.648075  6.6619053 8.968784 ]
 [8.669649  9.653931  9.576691 ]], shape=(3, 3), dtype=float32)


In [14]:
d = tf.range(start=1,limit=30,delta=5)
print(d)

tf.Tensor([ 1  6 11 16 21 26], shape=(6,), dtype=int32)


In [15]:
e = tf.cast(d,dtype=tf.float64) # converting dtype using cast
print(e)

tf.Tensor([ 1.  6. 11. 16. 21. 26.], shape=(6,), dtype=float64)


In [16]:
# mathematical operations
xx = tf.constant([1,2,3])
xy = tf.constant([4,5,6])


In [19]:
zz = tf.add(xx,xy)
print(zz)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [20]:
yy = tf.divide(xx,xy)
print(yy)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [22]:
yy = (xx/xy)
print(yy)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [23]:
# indexing
q = tf.constant([0,1,2,3,5])
print(q[:]) # will print all the elements


tf.Tensor([0 1 2 3 5], shape=(5,), dtype=int32)


In [24]:
print(q[:2])

tf.Tensor([0 1], shape=(2,), dtype=int32)


In [25]:
print(q[:-1])

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [26]:
print(q[::])

tf.Tensor([0 1 2 3 5], shape=(5,), dtype=int32)


In [29]:
print(q[1:])

tf.Tensor([1 2 3 5], shape=(4,), dtype=int32)


In [30]:
print(q[4:])

tf.Tensor([5], shape=(1,), dtype=int32)


In [31]:
print(q[1:3])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [32]:
print(q[::2])

tf.Tensor([0 2 5], shape=(3,), dtype=int32)


In [33]:
print(q[::-1]) # reverse

tf.Tensor([5 3 2 1 0], shape=(5,), dtype=int32)


In [38]:
indices = tf.constant([2,4])
x_ind = tf.gather(q,indices) # returns the gather index
print(x_ind)

tf.Tensor([2 5], shape=(2,), dtype=int32)


In [39]:
x = tf.constant([[1,2],
                 [3,4],[5,6]])
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [40]:
print(x[2,:])

tf.Tensor([5 6], shape=(2,), dtype=int32)


In [42]:
print(x[:])

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [44]:
print(x[0:1,:])

tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)


In [45]:
print(x[0:3,:])

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [50]:
# reshaping
x = tf.range(8)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)


In [51]:
x = tf.reshape(x,(2,4))
print(x)

tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int32)


In [59]:
x= tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor(
[[0 4]
 [1 5]
 [2 6]
 [3 7]], shape=(4, 2), dtype=int32)
